name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for taking your time to submit your first issue. This will be addressed soon."
        pr-message: "Welcome to ETA repo! Your contribution is much appreciated and will be taken care soon."
